# Site
repository: seolaf/resume
favicon: images/favicon.ico # Path to favicon (eg. images/favicon.ico)

# Content configuration version
version: 2

# Personal info
name: Jason Seo
name_ko: 서준우
title: Cybersecurity Engineer
email: holafaloh@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: seolaf.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
#github_username:  seolaf
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: junwoo-seo-5598481b9
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Scholar
  icon: fa fa-mortar-board
  url: https://scholar.google.com/citations?user=AAyFXG4AAAAJ&hl=en
- title: Dreamhack
  icon: fab fa-font-awesome-flag (https://fontawesome.com/v5/icons/font-awesome-flag?f=brands&s=solid)
  url: https://dreamhack.io/users/950/wargame
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Jason Seo. I'm a cybersecurity engineer with 7 years of experience, specializing in both offensive and defensive operations. Throughout my career, I've analyzed 50+ malware samples, detected 20+ security breaches at early stages, and designed 25 threat hunting scenarios that catch sophisticated threats. Concurrently, I pursued a Ph.D. program, strengthening my research capabilities. I address every challenge with enthusiasm, with a particular interest in threat hunting and continuously study to adapt and excel in diverse environments. Beyond personal growth, I value sharing knowledge with colleagues and take pride in cooperating effectively within any team.
about_content_ko: | 
  위협이 사고로 이어지기 전에 먼저 찾아내는 사이버보안 엔지니어 서준우입니다.
  
  공격과 방어 양측의 관점을 모두 경험하며, 정교한 탐지 시나리오를 설계하고 20건 이상의 침해 시도를 조기에 대응했습니다.
  
  기술적 깊이와 현장 경험을 바탕으로, 조직의 보안 수준을 강화하는 데 집중하고 있습니다.

content:
  - title: Professional Experience
    layout: list
    content:
      - layout: top
        title: Threat Detection, Analysis & Incident Response
        caption: 2020.09 - 2024.07 | R.O.K. Cyber Operations Command
        description: | 
          **Threat Detection & Analysis System Development**
          - Founding member of organization-wide Splunk deployment and operations, establishing enterprise security monitoring infrastructure
          - Designed and implemented 25 [SPL](https://docs.splunk.com/Splexicon:SPL)-based threat hunting scenarios and 10 monitoring dashboards
          - Successfully identified and mitigated 20+ security breaches at early stages, including supply chain attacks, APT campaigns, and large-scale data exfiltration
          - Led Splunk and threat hunting training programs for security analysts

          **Incident Response Leadership**
          - Led incident response and analysis teams for large-scale cyber threats including Log4j vulnerabilities and DDoS attacks
          - Conducted incident forensics and malware analysis to identify attacker TTPs and develop response strategies

          **Threat Hunting Operations**
          - Led proactive threat hunting operations across diverse network environments (internet-connected and isolated networks)
          - Conducted joint threat hunting operations with U.S. Cyber Command
          - Developed custom threat hunting frameworks and automation tools

              **Technology Stack**: <mark>Splunk</mark> <mark>QRadar</mark> <mark>Wireshark</mark> <mark>Zeek</mark> <mark>Arkime</mark> <mark>Security Onion</mark>

      - layout: top
        title: Threat Intelligence Collection & Analysis
        caption: 2022.07 - 2024.07 | R.O.K. Cyber Operations Command
        description: | 
          - Designed and deployed an automated threat intelligence collection and analysis system from OSINT and dark web sources (producing 100+ IoCs daily)
          - Reverse-engineered 50+ malware samples to extract and share Indicators of Compromise (IoCs)
          - Published and shared 10+ in-depth analysis reports on emerging malware families

              **Technology Stack**: <mark>IDA Pro</mark> <mark>Wireshark</mark> <mark>NetWitness NDR</mark> <mark>MISP</mark>

      - layout: top
        title: Vulnerability Research
        caption: 2020.09 - Present | R.O.K. Cyber Operations Command → Confidential
        description: | 
          - Identified 10+ web vulnerabilities including authentication bypass, insecure file uploads, and credential exposure\
          - Researched exploitation techniques for recently disclosed vulnerabilities (1-day) and conducted zero-day vulnerability research

              **Technology Stack**: <mark>Burp Suite</mark> <mark>Cobalt Strike</mark> <mark>IDA Pro</mark> <mark>Ghidra</mark> <mark>Docker</mark>


    content_ko:
      - layout: top
        title: 위협 탐지·분석 및 침해 대응
        caption: 2020.09 - 2024.07 | 사이버작전사령부 
        description: | 
          **위협 탐지·분석 시스템 구축 및 운영**
          - 전 군 Splunk 도입 및 운영 스타팅 멤버로 보안 모니터링 체계 구축
          - 25개의 [SPL](https://docs.splunk.com/Splexicon:SPL) 기반 위협 탐지 시나리오 및 10개의 모니터링 대시보드 설계 및 구현
          - 공급망 공격, APT 공격, 대규모 데이터 유출 등 20건 이상의 보안 침해를 초기 단계에서 탐지 및 대응
          - 사내 보안 분석가를 위한 분기별 Splunk 및 위협 헌팅 교육 프로그램 리드

          **침해 대응**
          - Log4j 취약점, DDoS 공격 등 대규모 사이버 위협에 대한 분석 대응팀 리드
          - 침해사고 포렌식 및 악성코드 분석을 통한 공격자 TTPs 식별 및 대응 전략 수립

          **위협 헌팅 작전 수행**
          - 다양한 네트워크 환경(인터넷망, 독립망 등)에서 위협 헌팅 작전 주도
          - 美 사이버사령부 합동 위협 헌팅 작전 수행
          - 맞춤형 헌팅 프레임워크 개발

              **Technology Stack**: <mark>Splunk</mark> <mark>QRadar</mark> <mark>Wireshark</mark> <mark>Zeek</mark> <mark>Arkime</mark> <mark>Security Onion</mark>

      - layout: top
        title: 위협정보 수집·분석 플랫폼 구축 및 운영
        caption: 2022.07 - 2024.07 | 사이버작전사령부
        description: | 
          - OSINT와 다크웹에서 위협정보를 자동 수집·분석하는 시스템 설계 및 구축 (일 평균 100+개의 침해지표 생산)
          - 50개 이상의 악성코드를 리버싱하여 침해지표(IoC) 분석 및 공유
          - 10개 이상의 신종 악성코드에 대한 심층 분석 보고서 발행 및 공유     

              **Technology Stack**: <mark>IDA Pro</mark> <mark>Wireshark</mark> <mark>NetWitness NDR</mark> <mark>MISP</mark>  

      - layout: top
        title: 취약점 분석
        caption: 2020.09 - 현재 | 사이버작전사령부 → 비공개 
        description: | 
          - 인증 우회, 안전하지 않은 파일 업로드, 자격증명 노출 등 10개 이상의 웹 취약점 식별
          - 최신 공개 취약점(1-day) 분석, 익스플로잇 기법 연구 및 제로데이 취약점 연구

              **Technology Stack**: <mark>Burp Suite</mark> <mark>Cobalt Strike</mark> <mark>IDA Pro</mark> <mark>Ghidra</mark> <mark>Docker</mark>

  - title: Work Experience
    layout: text
    content: |
      > **Vulnerability Analyst** | 2024.07 - Present  
      > *Confidential*
      
      > **Threat Intelligence Engineer** | 2022.07 - 2024.07  
      > *R.O.K. Cyber Operations Command*
      
      > **Threat Hunting Engineer** | 2020.09 - 2022.07  
      > *R.O.K. Cyber Operations Command*
      
      > **Security Technology Researcher** | 2019.08 - 2020.08  
      > *R.O.K. Cyber Operations Command*

      > **Undergraduate Research Assistant** | 2017.03 - 2019.02  
      > *Cyber Warfare Lab, Korea University*
  
    content_ko: |
      > **취약점 분석가** | 2024.07 - 현재  
      > *비공개*
      
      > **위협정보 엔지니어** | 2022.07 - 2024.07  
      > *사이버작전사령부*
      
      > **위협 헌팅 엔지니어** | 2020.09 - 2022.07  
      > *사이버작전사령부*
      
      > **보안기술 연구원** | 2019.08 - 2020.08  
      > *사이버작전사령부*

      > **인턴 연구원** | 2017.03 - 2019.02  
      > *고려대학교 사이버전 연구실*


  - title: Education
    layout: list
    content:
      - layout: left
        title: Korea University
        sub_title: Ph.D. Candidate
        caption: 2020.03 - Present
        quote: >
          School of Cybersecurity | Department of Information Security
        description: | # this will include new lines to allow paragraphs
          I am currently pursuing a Ph.D. in cybersecurity under the supervision of [Kyungho Lee](https://scholar.google.com/citations?view_op=list_works&hl=ko&user=jedqVOcAAAAJ&hl=en) and expanding my expertise into advanced areas of cybersecurity, with a particular focus on AI and Big Data.

          I conducted research on CTI based on the MITRE ATT&CK Framework to model and analyze sophisticated threat actors and their tactics, techniques, and procedures.

          My research has also encompassed the field of blockchain security. I have worked on cryptocurrency incident analysis, illicit transaction tracking, and improved detection methods for cryptocurrency-based money laundering.
      - layout: left
        title: Korea University
        sub_title: B.S. in Cyber Defense, <br>IT Convergence Security
        caption: 2015.03 - 2019.02
        quote: >
          Division of Information Security | Department of Cyber Defense
        description: | # this will include new lines to allow paragraphs
          As a student majoring in cybersecurity, I completed a rigorous academic program that provided me with a strong foundation in core concepts of cybersecurity such as network security, cryptography, digital forensics, and vulnerability analysis.

          I have also developed a deep understanding of domestic and international cybersecurity laws and regulations, including Network Act, Personal Information Protection Act, GDPR, and the Tallinn Manual.

          I was challenged to apply my knowledge to real-world cyber threats and security issues by participating in hands-on projects and research opportunities, and I developed my problem-solving and critical thinking skills by collaborating with my peers.

    content_ko: 
      - layout: left
        title: 고려대학교
        sub_title: 정보보안학과 석박사통합과정 수료
        caption: 2020.03 - Present
          
      - layout: left
        title: 고려대학교
        sub_title: 사이버국방학과 학사
        caption: 2015.03 - 2019.02


  - title: Certifications
    layout: list
    content:
      - layout: top-middle
        title: Engineer Information Security
        caption : 2024.09 - 
      - layout: top-middle
        title: Big-Data Analysis Engineer
        caption : 2023.07 -
      - layout: top-middle
        title: Engineer Information Processing
        caption : 2018.11 -
    content_ko:
      - layout: top-middle
        title: 정보보안기사
        caption : 2024.09 - 
      - layout: top-middle
        title: 빅데이터분석기사
        caption : 2023.07 -
      - layout: top-middle
        title: 정보처리기사
        caption : 2018.11 -    

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - **Seo, J.**, Kim, K., Park, M., Park, M., & Lee, K. (2018). An analysis of economic impact on IoT industry under GDPR. Mobile Information Systems, 2018(1), 6792028. [[PAPER]](https://onlinelibrary.wiley.com/doi/full/10.1155/2018/6792028)
      - Park, M., **Seo, J.**, Han, J., Oh, H., & Lee, K. (2018). Situational Awareness Framework for Threat Intelligence Measurement of Android Malware. J. Wirel. Mob. Networks Ubiquitous Comput. Dependable Appl., 9(3), 25-38. [[PAPER]](https://isyou.info/jowua/papers/jowua-v9n3-3.pdf)
      - **Seo, J.**, Park, M., Oh, H., & Lee, K. (2018, October). Money laundering in the bitcoin network: Perspective of mixing services. In 2018 International Conference on Information and Communication Technology Convergence (ICTC) (pp. 1403-1405). IEEE. [[PAPER]](https://ieeexplore.ieee.org/abstract/document/8539548)

      - Joo, M., **Seo, J.**, Oh, J., Park, M., & Lee, K. (2018, July). Situational awareness framework for cyber crime prevention model in cyber physical system. In 2018 tenth international conference on ubiquitous and future networks (icufn) (pp. 837-842). IEEE. [[PAPER]](https://ieeexplore.ieee.org/abstract/document/8436591)
      - Park, M., **Seo, J.**, Han, J., Oh, H., & Lee, K. (2018, June). Situational Awareness for Hybrid Warfare: Risk Measurement Between Cyber Warfare and Nuclear Warfare. In ECCWS 2018 17th European Conference on Cyber Warfare and Security (Vol. 2, p. 360). [[PAPER]](https://books.google.co.kr/books?hl=ko&lr=&id=-kFmDwAAQBAJ&oi=fnd&pg=PA360&dq=Situational+Awareness+for+Hybrid+Warfare:+Risk+Measurement+Between+Cyber+Warfare+and+Nuclear+Warfare&ots=ZFOWQdtf2t&sig=OIWezHkqad6xDlNs_c2Dc85qtpg&redir_esc=y#v=onepage&q=Situational%20Awareness%20for%20Hybrid%20Warfare%3A%20Risk%20Measurement%20Between%20Cyber%20Warfare%20and%20Nuclear%20Warfare&f=false)
      - Joo, M., **Seo, J.**, Park, M., Oh, H. R., & Lee, K. (2018, June). Possibility of Using Cyber-PYSOP Through Nuclear Weapon: Symbolic Meaning and Risk Measurement of Nuclear Weapon in Social Network. In ECCWS 2018 17th European Conference on Cyber Warfare and Security V2 (p. 233). Academic Conferences and publishing limited. [[PAPER]](https://books.google.co.kr/books?hl=ko&lr=&id=-kFmDwAAQBAJ&oi=fnd&pg=PA233&dq=Possibility+of+Using+Cyber-PYSOP+Through+Nuclear+Weapon:+Symbolic+Meaning+and+Risk+Measurement+of+Nuclear+Weapon+in+Social+Network&ots=ZFOWQdth-o&sig=FZLvp9IE_Tdrj9FjZfvwrImzf3Q&redir_esc=y#v=onepage&q=Possibility%20of%20Using%20Cyber-PYSOP%20Through%20Nuclear%20Weapon%3A%20Symbolic%20Meaning%20and%20Risk%20Measurement%20of%20Nuclear%20Weapon%20in%20Social%20Network&f=false)
      - Park, M., Joo, M., **Seo, J.**, Kim, K., Park, M., & Lee, K. (2018, January). Complex Network of Damage Assessment Using GMM Based FAIR. In 2018 IEEE International Conference on Big Data and Smart Computing (BigComp) (pp. 627-630). IEEE. [[PAPER]](https://ieeexplore.ieee.org/abstract/document/8367191)
      - Kim, K., **Seo, J.**, Park, M., Park, M., & Lee, K. (2018). A Cyber Command and Control Framework for Psychological Operation Using Social Media. Journal of Telecommunication, Electronic and Computer Engineering (JTEC), 10(4), 101-105. [[PAPER]](https://jtec.utem.edu.my/jtec/article/view/4792)
      - Park, M., **Seo, J.**, Kim, K., Park, M., & Lee, K. (2017, October). Criminal Minds: Reasoning Prime Suspect in Russian Hacking Scandal by Perspective of Insiders. In Proceedings of the 2017 International Workshop on Managing Insider Security Threats (pp. 97-100). [[PAPER]](https://dl.acm.org/doi/abs/10.1145/3139923.3139936)
    content_ko: | # this will include new lines to allow paragraphs
      - **Seo, J.**, Kim, K., Park, M., Park, M., & Lee, K. (2018). An analysis of economic impact on IoT industry under GDPR. Mobile Information Systems, 2018(1), 6792028. [[PAPER]](https://onlinelibrary.wiley.com/doi/full/10.1155/2018/6792028)
      - Park, M., **Seo, J.**, Han, J., Oh, H., & Lee, K. (2018). Situational Awareness Framework for Threat Intelligence Measurement of Android Malware. J. Wirel. Mob. Networks Ubiquitous Comput. Dependable Appl., 9(3), 25-38. [[PAPER]](https://isyou.info/jowua/papers/jowua-v9n3-3.pdf)
      - **Seo, J.**, Park, M., Oh, H., & Lee, K. (2018, October). Money laundering in the bitcoin network: Perspective of mixing services. In 2018 International Conference on Information and Communication Technology Convergence (ICTC) (pp. 1403-1405). IEEE. [[PAPER]](https://ieeexplore.ieee.org/abstract/document/8539548)
      <details>
      <summary>전체 논문 보기</summary>
      <br>
      - Joo, M., **Seo, J.**, Oh, J., Park, M., & Lee, K. (2018). Situational awareness framework for cyber crime prevention model in cyber physical system. *IEEE ICUFN*, 837-842. <a href="https://ieeexplore.ieee.org/abstract/document/8436591">[PAPER]</a><br>
      - Park, M., **Seo, J.**, Han, J., Oh, H., & Lee, K. (2018). Situational Awareness for Hybrid Warfare: Risk Measurement Between Cyber Warfare and Nuclear Warfare. *ECCWS 2018*, Vol. 2, p. 360. <a href="https://books.google.co.kr/books?hl=ko&lr=&id=-kFmDwAAQBAJ&oi=fnd&pg=PA360">[PAPER]</a><br>
      - Joo, M., **Seo, J.**, Park, M., Oh, H. R., & Lee, K. (2018). Possibility of Using Cyber-PYSOP Through Nuclear Weapon. *ECCWS 2018 V2*, p. 233. <a href="https://books.google.co.kr/books?hl=ko&lr=&id=-kFmDwAAQBAJ&oi=fnd&pg=PA233">[PAPER]</a><br>
      - Park, M., Joo, M., **Seo, J.**, Kim, K., Park, M., & Lee, K. (2018). Complex Network of Damage Assessment Using GMM Based FAIR. *IEEE BigComp*, 627-630. <a href="https://ieeexplore.ieee.org/abstract/document/8367191">[PAPER]</a><br>
      - Kim, K., **Seo, J.**, Park, M., Park, M., & Lee, K. (2018). A Cyber Command and Control Framework for Psychological Operation Using Social Media. *JTEC*, 10(4), 101-105. <a href="https://jtec.utem.edu.my/jtec/article/view/4792">[PAPER]</a><br>
      - Park, M., **Seo, J.**, Kim, K., Park, M., & Lee, K. (2017). Criminal Minds: Reasoning Prime Suspect in Russian Hacking Scandal by Perspective of Insiders. *MIST 2017*, 97-100. <a href="https://dl.acm.org/doi/abs/10.1145/3139923.3139936">[PAPER]</a>
      </details>

  - title: Activities and Awards # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - **4th Place** at the 2024 WhiteHat Contest (2024)
      - **3rd Place** (Korea Internet & Security Agency Award) at the Cyber Talpiot Hackathon (2023) 
      - **4th Place** at the Splunk Korea 2023 BOTS (Boss of the SOC) (2023)
      - Led a specialized team for the ASEAN Defense Ministers' Meeting-Plus (ADMM-Plus) Cyber Training and Exercise (CYTREX). (2023) [[Media]](https://www.news1.kr/politics/diplomacy-defense/5226891) 
      - Commendation by the Commander of ROK Cyber Operations Command (2023)
      - Commendation by the Commander of Defense Security Agency (2023)
      - Letter of Appreciation from the Commander, Cyber National Mission Force, U.S. Cyber Command (2023)
      - Commendation by the Chief of ROK Army Cyber Operations Center (2022)
      - Commendation by the Commander of ROK Cyber Operations Command (2021)
      - **1st Place** (Korea Institute of Information Security & Cryptology Award) in the AI Detection Category at the 2019 K-Cyber Security Challenge (2019)
      - Future Talent Award from the Commissioner of Defense Acquisition Program Administration (DAPA) (2018)

    content_ko: | # this will include new lines to allow paragraphs
      - 화이트햇 콘테스트 본선 **4위** (2024)
      - 사이버 탈피오트 해커톤 본선 **3위** (KISA 원장상) (2023) 
      - Splunk 2023 BOTS(Boss of the SOC) 본선 **4위** (2023)
      - ADMM-Plus(ASEAN Defense Ministers' Meeting-Plus) CYTREX(Cyber Training and Exercise) **공동 1위** (2023) [[미디어]](https://www.news1.kr/politics/diplomacy-defense/5226891) 
      - 사이버작전사령관 표창 (2023)
      - 777사령관 표창 (2023)
      - 美 사이버사령부 사이버 국가 임무 부대(CNMF) 부대장 감사장 (2023)
      - 육군 사이버작전센터장 표창(2022)
      - 사이버작전사령관 표창 (2021)
      - K-사이버 시큐리티 챌린지 AI 탐지 부문 **1위** (정보보호학회장상) (2019)
      - 방위사업청장 미래인재상 (2018)      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
