# Site
repository: seolaf/resume (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico # Path to favicon (eg. images/favicon.ico)

# Content configuration version
version: 2

# Personal info
name: Jason Seo
title: Cybersecurity Engineer
email: holafaloh@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: seolaf.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  seolaf
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
orcid_username: 0000-0000-0000-0000
googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Dreamhack
  icon: fab fa-font-awesome-flag (https://fontawesome.com/v5/icons/font-awesome-flag?f=brands&s=solid)
  url: https://dreamhack.io/users/950/wargame
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>
    - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: | 
          Confidential
        sub_title: Vulnerability Engineer <br></b>(as Capt, ROK Army)<b>
        caption: 2024.07 - present
        #link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
      - layout: left
        title: R.O.K. <br>Cyber Operations Command
        sub_title: Threat Intelligence Engineer <br></b>(as Capt, ROK Army)<b>
        caption: 2022.07 - 2024.07
        #link: Link to company (optional)
        quote: >
          R.O.K. Cyber Operations Command is unit under the direct control of the MND for conducting cyber operations in cyberspace
        description: | # this will include new lines to allow paragraphs
          - Collected threat intelligence from OSINT and dark web, developing an automated analysis system to enhance proactive threat detection.
          - Reverse-engineered 50+ malware samples, extracting and sharing Indicators of Compromise(IoCs) with both the National Cyber Security Center(NCSC) and U.S. Cyber Command.
          - Authored and shared 10+ in-depth analysis reports on emerging malware to partner organizations.
          - Conducted multiple threat hunting operations independently(ROK-only) and in collaboration with U.S. Cyber Command.

              **Technology Stack**: <mark>IDA Pro</mark>  <mark>Wireshark</mark>  <mark>NetWitness NDR</mark>  <mark>MISP</mark>  <mark>Shodan</mark>  <mark>VMware vSphere</mark>
      - #title: ROK Cyber Operations Command              
        sub_title: Threat Hunting Engineer <br></b>(as 1st Lt, ROK Army)<b>
        caption: 2020.09 - 2022.07
        description: | # this will include new lines to allow paragraphs
          - Designed and implemented 25 [SPL](https://docs.splunk.com/Splexicon:SPL)-based threat hunting scenarios and 10 monitoring dashboards to visiualize detection results and enhance situational awareness.
          - Successfully identified and mitigated 20+ security breaches in early stages, including supply chain attacks, spear phishing, and data exfiltration.
          - Discovered and analyzed 10+ web vulnerabilites, including authentication bypass, file upload vulnerabilities, and plaintext credential transmission.
          - Led incident response and analysis team for large-scale cyber threats such as Log4j vulnerabilities and DDoS attacks.
          - Designed and taught a training program on Splunk and threat hunting techniques for security analysts.

              **Technology Stack**: <mark>Splunk</mark>  <mark>QRadar</mark>  <mark>Wireshark</mark>  <mark>Zeek</mark>  <mark>Arkime</mark>  <mark>Security Onion</mark>  <mark>Snort</mark>  <mark>Suricata</mark> 
      - #title: ROK Cyber Operations Command
        sub_title: Researcher and Developer <br></b>(as 2nd Lt, ROK Army)<b>
        caption: 2019.08 - 2020.08
        description: | # this will include new lines to allow paragraphs
          - Conducted vulnerability analysis of Korean open-source operating systmes(HamoniKR OS, GooroomOS, TmaxOS).
          - Researched AI implementation for military intrusion detection systems using KISA information security R&D datasets.
          - Designed and Developed 3 specialized programs to support cyber operations.

              **Technology Stack**: <mark>C/C++</mark>  <mark>Python</mark>  <mark>TensorFlow</mark>  <mark>PyTorch</mark>  <mark>Scikit-learn</mark>
      - layout: left
        title: Cyber Warfare Lab, Korea University 
        sub_title: Undergraduate Research Assistant
        caption: 2017.03 - 2019.02
        quote: >
          Cyber Warfare Lab is a specialized lab for research and development of defense technologies related to cyberwarfare.
        description: | # this will include new lines to allow paragraphs
          - Designed and developed a framework for cyber Command & Control(C2) system.
          - Designed and developed a software that utilized [STIX](https://oasis-open.github.io/cti-documentation/stix/intro.html) and [TAXII](https://oasis-open.github.io/cti-documentation/taxii/intro.html) to produce and share Cyber Threat Intelligence(CTI).

              **Technology Stack**: <mark>Python</mark>  <mark>Java</mark>  <mark>SQL</mark>  <mark>REST API</mark>  <mark>GraphQL</mark>  <mark>Docker</mark>  <mark>AWS</mark>  <mark>Elasticsearch (ELK)</mark>  <mark>MITRE ATT&CK</mark>
  - title: Education
    layout: list
    content:
      - layout: left
        title: Korea University
        sub_title: Ph.D. Candidate
        caption: 2020.03 - Present
        quote: >
          School of Cybersecurity | Department of Information Security
        description: | # this will include new lines to allow paragraphs
          I am currently pursuing a Ph.D. in cybersecurity under the supervision of [Kyungho Lee](https://scholar.google.com/citations?view_op=list_works&hl=ko&user=jedqVOcAAAAJ&hl=en) and expanding my expertise into advanced areas of cybersecurity, with a particular focus on AI and Big Data.

          I conducted research on CTI based on the MITRE ATT&CK Framework to model and analyze sophisticated threat actors and their tactics, techniques, and procedures.

          My research has also encompassed the field of blockchain security. I have worked on cryptocurrency incident analysis, illicit transaction tracking, and improved detection methods for cryptocurrency-based money laundering.
      - layout: left
        title: Korea University
        sub_title: B.S. in Cyber Defense, <br>IT Convergence Security
        caption: 2015.03 - 2019.02
        quote: >
          Division of Information Security | Department of Cyber Defense
        description: | # this will include new lines to allow paragraphs
          As a student majoring in cybersecurity at the Korea University, I completed a rigorous academic program that provided me with a strong foundation in core concepts of cybersecurity such as network security, cryptography, digital forensics, and vulnerability analysis.

          I have also developed a deep understanding of domestic and international cybersecurity laws and regulations, including Network Act, Personal Information Protection Act, GDPR, and the Tallinn Manual.

          I was challenged to apply my knowledge to real-world cyber threats and security issues by participating in hands-on projects and research opportunities, and I developed my problem-solving and critical thinking skills by collaborating with my peers.
  - title: Certifications
    layout: list
    content:
      - layout: top-middle
        title: Engineer Information Security
        caption : 2024.09 - 
      - layout: top-middle
        title: Big-Data Analysis Engineer
        caption : 2023.07 -
      - layout: top-middle
        title: Engineer Information Processing
        caption : 2018.11 -

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - Kim, K., **Seo, J.**, Park, M., Park, M., & Lee, K. (2018). A Cyber Command and Control Framework for Psychological Operation Using Social Media. Journal of Telecommunication, Electronic and Computer Engineering (JTEC), 10(4), 101-105. [[PAPER]](https://jtec.utem.edu.my/jtec/article/view/4792)
      - **Seo, J.**, Park, M., Oh, H., & Lee, K. (2018, October). Money laundering in the bitcoin network: Perspective of mixing services. In 2018 International Conference on Information and Communication Technology Convergence (ICTC) (pp. 1403-1405). IEEE. [[PAPER]](https://ieeexplore.ieee.org/abstract/document/8539548)
  - title: Avtivities and Awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project 

  - title: Publication
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
